### ISSUE TITLE
Extension Installed by GPO isn't being updated

### ISSUE THREAD

**Issue by sasadipo** [mozilla/policy-templates#207]
Installed extensions by filepath (and enforced through the policies below) aren't being updated when the local XPI file changes:

{
  "policies": {
    "Extensions": {
            "Installed": ["C:\\Filepath\Extension.xpi"]
            "Locked":  ["addon_id@mozilla.org"]
    }
} 

Changing the local file name and adding a new value under the policy will create 2 extensions in Firefox. 
It looks like the old extension is being cached by Firefox, and AFAIK there's no way to clear the cache.

**Comment by mkaply** [comment]
We have no way to know the extension changed and we don't want to install it at every update.

We're investigating a "ForceInstall" GPO but for now the easiest thing to do is add the version number to the XPI and change it each time.

**Comment by sasadipo** [comment]
Your suggestion results in two firefox extensions being installed in ff 62beta15

Regards,
Sean Asadipour

**Comment by mkaply** [comment]
That shouldn't happen. Does the same extension install twice?

**Comment by sasadipo** [comment]
Yes, i see 2 versions of the same extension.

**Comment by sasadipo** [comment]
Hi @mkaply,
Are you or anyone from your team able to reproduce this issue?

> We have no way to know the extension changed and we don't want to install it at every update.
Do you mean every GPO update?
I don't think the extension necessarily needs to be updated at every GPO update. However, for locally installed extensions, I'm having trouble understanding why firefox can't just check for a version change or compare file hashes on the original extension for every GPO update and subsequently update the cached version?

**Comment by mkaply** [comment]
> I'm having trouble understanding why firefox can't just check for a version change or compare file hashes on the original extension for every GPO update and subsequently update the cached version?

That would be more information we would have to store and it wouldn't work for extensions at URLs. I have some other ideas I'll be looking into.

I did test simply changing the name of the extension and it worked fine for me. I did not end up with two versions of the extension - the latest version replaced the older version.

What extension were you trying to install?

**Comment by sasadipo** [comment]
> I did test simply changing the name of the extension and it worked fine for me. I did not end up with two versions of the extension - the latest version replaced the older version

huh, that's odd. Which ff build did you use to test? Did the extensions have the same extension id? 
Did you set the policy through GPO (registry)?

**Comment by sasadipo** [comment]
Hi @mkaply,
Thanks again for your assistance. I just tested the proposed workaround again with the v62 release build, and found that the issue still exists (two extensions show up - only one is "Locked")
> That would be more information we would have to store and it wouldn't work for extensions at URLs. I have some other ideas I'll be looking into.
Can you please provide some background on this plan? Is there an official bug on bugzilla we can use to track this issue to resolution?

**Comment by mkaply** [comment]
Can you please post a screenshot of this situation? This should be impossible.

**Comment by sasadipo** [comment]
![capture](https://user-images.githubusercontent.com/8535672/45265579-031d8280-b402-11e8-95dd-1348f51685bc.PNG)

**Comment by mkaply** [comment]
> Can you please provide some background on these ideas? Also, Is there an official bug on bugzilla we can use to track this issue to resolution?

Nothing to report yet.

> This is very easy to replicate - this shouldn't be a problem to reproduce. Can you please answer my earlier questions?

I can't reproduce this at all with add-ons from AMO.

Is this extension signed via AMO or unsigned? Does the manifest.json have a ID in it?

**Comment by sasadipo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1490135

**Comment by mkaply** [comment]
This was fixed in bugzilla. Also our new ExtensionSettings policy does this much better.

**Comment by sasadipo** [comment]
Issue still exists on Fresh install of Firefox 68.01 ESR release and quantum - please reopen
