### ISSUE TITLE
Intune | error on  B_WebsiteFilter_Block

### ISSUE THREAD

**Issue by dneto-ame** [mozilla/policy-templates#789]
Hi eveyrone. I dont know if i'm doing something wrong. 

I have very similar deployment for Chrome Browsers, so ADMX Ingestion and some settings via OMA-URI.
All seems correct checked on Configuration Profile status, but his special one, coping exactly same data from [example](https://github.com/mozilla/policy-templates#websitefilter).

My case is applying:
OMA=URI
`./Device/Vendor/MSFT/Policy/Config/Firefox~Policy~firefox/B_WebsiteFilter_Block`

String Value:
```
<enabled/>
<data id="WebsiteFilter" value="1&#xF000;<all_urls>"/>
```
 
On browser:
![image](https://user-images.githubusercontent.com/53838590/127600563-94949a64-8ef9-45bb-8f7c-064c2ff09cce.png)
![image](https://user-images.githubusercontent.com/53838590/127600597-842a7135-5de6-419e-be9f-39438208e5f6.png)

At MEM:
![image](https://user-images.githubusercontent.com/53838590/127600655-4c131ea8-7932-4506-b9ac-c3d609f704b1.png)

What I'm missing? 

Actually I'm really trying to block all URLS for Firefox. Just do make clear what seems crazy. :D

**Comment by mkaply** [comment]
Can you try *://*?

I don't think we support * as a pattern.

IF that doesn't work, http://* and https://*

**Comment by mkaply** [comment]
If that works, I'll update our code to map * to that.

**Comment by dneto-ame** [comment]
Hi @mkaply . Thanks for your attention.

I just tried 
`*://*?`
Seems applied correctly:
![image](https://user-images.githubusercontent.com/53838590/127782035-b40133c3-fea0-4710-9256-932694bf89c7.png)
But still error on App side:
![image](https://user-images.githubusercontent.com/53838590/127782059-6e40945d-62ac-4a04-a8d5-c2867a87f614.png)
![image](https://user-images.githubusercontent.com/53838590/127782067-47476afc-df6f-4af4-8631-a017e79e5653.png)

I also tried to pass by protocol (HTTP and HTTPS), without success
![image](https://user-images.githubusercontent.com/53838590/127782748-88284fcd-8e57-45a2-9caa-93e9b8e74f26.png)

**Comment by mkaply** [comment]
I'll run some tests and see what's going on.

**Comment by dneto-ame** [comment]
I was looking on windows logs. Seems something related to escape. Windows CSP is not interpreting escape value, so on logs I'm receiving an "unspecified error"

![image](https://user-images.githubusercontent.com/53838590/127788848-b58dcfa9-142c-42c3-8c8b-25e4a38e67ed.png)


![image](https://user-images.githubusercontent.com/53838590/127788835-48f31414-e288-496c-b035-6ab9c9a98cfa.png)

googling around I found some similar problems regarding escape:
https://github.com/MicrosoftDocs/windows-itpro-docs/issues/856

**Comment by dneto-ame** [comment]
Hi. I managed to deploy config as:
`<enabled/>
<data id="WebsiteFilter" value="1&#xF000;*://*/*"/>`

Not covering all schemes, but suitable. :D

**Comment by mkaply** [comment]
Interesting. I'll still do some testing :)

**Comment by mkaply** [comment]
So I completely forgot we use the same match pattern as web extensions

So you can just use

<all_urls>

I'm still looking at why the others don't work

**Comment by mkaply** [comment]
And you are correct, based on the docs, the correct pattern for everything is *://*/*

I'll update the docs to specifically mention this.

**Comment by mkaply** [comment]
I've updated the docs to be more precise. Thanks for pointing this out.

**Comment by dneto-ame** [comment]
Hi @mkaply , thanks for you reply. 

Sorry but I'm still not get why suggested value on doc, wasn't working:
`<enabled/> <data id="WebsiteFilter" value="1&#xF000;<all_urls>"/>`
This value as suggested leads to error on Intune processing.

Only this value was processed: 
`<enabled/> <data id="WebsiteFilter" value="1&#xF000;*://*/*"/>`

But in this case, I cannot block all schemas in accordance with [docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns).

So there is a way to enforce the behaviour from <all_users>

**Comment by mkaply** [comment]
You're right, in intune you'll have to use entities for the <> 

try &lt;all_urls&gt;

I'll fix that in my intune example.

**Comment by mkaply** [comment]
Just to be save, it should be:

```
&#60;all_users&#62;
```

**Comment by dneto-ame** [comment]
@mkaply Thanks. I really appreciate your attention. 
Sorry for "all_users", i misspelled and you follow. :D (lets fix together)

Good news:
`<enabled/> <data id="WebsiteFilter" value="1&#xF000;&#60;all_urls&#62;"/>`

Worked as expected:
![image](https://user-images.githubusercontent.com/53838590/128560063-56ca49a1-164c-4328-904f-58e4fe8e4991.png)
